

FT_DPCM_PTR=$c000
	.export _boatSong_music_data
;this file for FamiTone2 library generated by text2data tool
_boatSong_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256




@instruments:
	.byte $30 ;instrument 00 (Duty 0)
	.word @env1, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 01 (Duty 2)
	.word @env1, @env0, @env0
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$38,$0f	;1 (Sample 1)
	.byte $0e+.lobyte(FT_DPCM_PTR),$35,$0f	;2 (Sample 2)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;16 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;18 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;20 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;21 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;22 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;23 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;25 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;26 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;27 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;28 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;29 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;30 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;31 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;32 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;33 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;34 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;35 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;36 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;37 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63 

@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $cf,$7f,$00,$00

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@ref0:
	.byte $82,$52,$91,$50,$a5,$4c,$a5,$5a,$b9,$56,$a5,$52,$a5,$56,$a5,$5a,$f9,$a3,$56,$91,$60,$91,$5a,$9d
@ref1:
	.byte $af,$56,$91,$52,$91,$4c,$91,$50,$91,$52,$91,$50,$a5,$4c,$a5,$5a,$b9,$56,$a5,$52,$a5,$56,$a5,$5a,$a5,$50,$bd
@ref2:
	.byte $a3,$60,$b9,$64,$91,$60,$a5,$5a,$b9,$4c,$91,$50,$91,$52,$91,$50,$a5,$4c,$a5,$5a,$b9,$56,$a5,$52,$a5,$56,$8d
@ref3:
	.byte $97,$5a,$f9,$a3,$56,$91,$60,$91,$5a,$cd,$56,$91,$52,$91,$4c,$91,$50,$91,$52,$91,$50,$a5,$4c,$a5,$5a,$99
@ref4:
	.byte $9f,$56,$a5,$52,$a5,$56,$a5,$5a,$a5,$50,$e1,$60,$b9,$64,$91,$60,$a5,$5a,$b9,$60,$91,$64,$91
@ref5:
	.byte $52,$91,$50,$a5,$4c,$a5,$5a,$b9,$56,$a5,$52,$a5,$56,$a5,$5a,$f9,$a3,$56,$91,$60,$91,$5a,$9d
	.byte $ff,$1b
	.word @ref1
	.byte $ff,$1b
	.word @ref2
	.byte $ff,$1a
	.word @ref3
	.byte $ff,$17
	.word @ref4
	.byte $ff,$17
	.word @ref5
	.byte $ff,$1b
	.word @ref1
	.byte $ff,$1b
	.word @ref2
	.byte $ff,$1a
	.word @ref3
	.byte $ff,$17
	.word @ref4
	.byte $ff,$17
	.word @ref5
	.byte $ff,$1b
	.word @ref1
	.byte $ff,$1b
	.word @ref2
	.byte $ff,$1a
	.word @ref3
	.byte $ff,$17
	.word @ref4
	.byte $ff,$17
	.word @ref5
	.byte $ff,$1b
	.word @ref1
	.byte $ff,$1b
	.word @ref2
	.byte $ff,$1a
	.word @ref3
	.byte $ff,$17
	.word @ref4
	.byte $ff,$17
	.word @ref5
	.byte $ff,$1b
	.word @ref1
	.byte $ff,$1b
	.word @ref2
	.byte $ff,$1a
	.word @ref3
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref6:
	.byte $89,$82,$52,$91,$50,$a5,$4c,$a5,$5a,$b9,$56,$a5,$52,$a5,$56,$a5,$5a,$f9,$a3,$56,$91,$60,$91,$5a,$93
@ref7:
	.byte $b9,$56,$91,$52,$91,$4c,$91,$50,$91,$52,$91,$50,$a5,$4c,$a5,$5a,$b9,$56,$a5,$52,$a5,$56,$a5,$5a,$a5,$50,$b3
@ref8:
	.byte $ad,$60,$b9,$64,$91,$60,$a5,$5a,$b9,$4c,$91,$50,$91,$52,$91,$50,$a5,$4c,$a5,$5a,$b9,$56,$a5,$52,$a5,$56,$83
@ref9:
	.byte $a1,$5a,$f9,$a3,$56,$91,$60,$91,$5a,$cd,$56,$91,$52,$91,$4c,$91,$50,$91,$52,$91,$50,$a5,$4c,$a5,$5a,$8f
@ref10:
	.byte $a9,$56,$a5,$52,$a5,$56,$a5,$5a,$a5,$50,$e1,$60,$b9,$64,$91,$60,$a5,$5a,$b9,$60,$91,$64,$87
@ref11:
	.byte $89,$52,$91,$50,$a5,$4c,$a5,$5a,$b9,$56,$a5,$52,$a5,$56,$a5,$5a,$f9,$a3,$56,$91,$60,$91,$5a,$93
	.byte $ff,$1b
	.word @ref7
	.byte $ff,$1b
	.word @ref8
	.byte $ff,$1a
	.word @ref9
	.byte $ff,$17
	.word @ref10
	.byte $ff,$18
	.word @ref11
	.byte $ff,$1b
	.word @ref7
	.byte $ff,$1b
	.word @ref8
	.byte $ff,$1a
	.word @ref9
	.byte $ff,$17
	.word @ref10
	.byte $ff,$18
	.word @ref11
	.byte $ff,$1b
	.word @ref7
	.byte $ff,$1b
	.word @ref8
	.byte $ff,$1a
	.word @ref9
	.byte $ff,$17
	.word @ref10
	.byte $ff,$18
	.word @ref11
	.byte $ff,$1b
	.word @ref7
	.byte $ff,$1b
	.word @ref8
	.byte $ff,$1a
	.word @ref9
	.byte $ff,$17
	.word @ref10
	.byte $ff,$18
	.word @ref11
	.byte $ff,$1b
	.word @ref7
	.byte $ff,$1b
	.word @ref8
	.byte $ff,$1a
	.word @ref9
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref12:
	.byte $81,$80,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2a,$8f,$00,$42,$87
@ref13:
	.byte $87,$00,$2a,$8f,$00,$42,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$2a,$8f,$00,$42
@ref14:
	.byte $8f,$00,$2a,$8f,$00,$42,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8b
@ref15:
	.byte $83,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$83
@ref16:
	.byte $8b,$00,$44,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$2a,$8f,$00,$42,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f
@ref17:
	.byte $00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$34,$8f,$00,$4c,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$30,$8f,$00,$48,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2c,$8f,$00,$44,$8f,$00,$2a,$8f,$00,$42,$87
	.byte $ff,$4e
	.word @ref13
	.byte $ff,$4c
	.word @ref14
	.byte $ff,$4f
	.word @ref15
	.byte $ff,$4c
	.word @ref16
	.byte $ff,$4e
	.word @ref17
	.byte $ff,$4e
	.word @ref13
	.byte $ff,$4c
	.word @ref14
	.byte $ff,$4f
	.word @ref15
	.byte $ff,$4c
	.word @ref16
	.byte $ff,$4e
	.word @ref17
	.byte $ff,$4e
	.word @ref13
	.byte $ff,$4c
	.word @ref14
	.byte $ff,$4f
	.word @ref15
	.byte $ff,$4c
	.word @ref16
	.byte $ff,$4e
	.word @ref17
	.byte $ff,$4e
	.word @ref13
	.byte $ff,$4c
	.word @ref14
	.byte $ff,$4f
	.word @ref15
	.byte $ff,$4c
	.word @ref16
	.byte $ff,$4e
	.word @ref17
	.byte $ff,$4e
	.word @ref13
	.byte $ff,$4c
	.word @ref14
	.byte $ff,$4f
	.word @ref15
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref18:
	.byte $f9,$f9,$f9,$f9,$97
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $ff,$05
	.word @ref18
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref19:
	.byte $02,$a5,$02,$a5,$02,$a5,$02,$91,$02,$91,$02,$a5,$02,$a5,$02,$a5,$02,$91,$02,$91,$02,$a5,$02,$a5,$02,$a5,$02,$91,$02,$91,$02,$9d
@ref20:
	.byte $87,$02,$a5,$02,$a5,$02,$91,$02,$91,$02,$a5,$02,$a5,$02,$a5,$02,$91,$02,$91,$02,$a5,$02,$a5,$02,$a5,$02,$91,$02,$91,$02,$a5,$02,$95
@ref21:
	.byte $8f,$02,$a5,$02,$91,$02,$91,$02,$a5,$02,$a5,$02,$a5,$02,$91,$02,$91,$02,$a5,$04,$a5,$02,$a5,$04,$a5,$02,$a5,$04,$a5,$02,$8d
@ref22:
	.byte $97,$04,$91,$04,$91,$02,$a5,$04,$a5,$02,$a5,$04,$a5,$02,$a5,$04,$a5,$02,$a5,$04,$91,$04,$91,$02,$a5,$04,$a5,$02,$a5,$04,$85
@ref23:
	.byte $9f,$02,$a5,$04,$a5,$02,$a5,$04,$91,$04,$91,$02,$a5,$04,$a5,$02,$a5,$04,$a5,$02,$a5,$04,$a5,$02,$a5,$04,$91,$04,$91
	.byte $ff,$20
	.word @ref19
	.byte $ff,$21
	.word @ref20
	.byte $ff,$1f
	.word @ref21
	.byte $ff,$1f
	.word @ref22
	.byte $ff,$1d
	.word @ref23
	.byte $ff,$20
	.word @ref19
	.byte $ff,$21
	.word @ref20
	.byte $ff,$1f
	.word @ref21
	.byte $ff,$1f
	.word @ref22
	.byte $ff,$1d
	.word @ref23
	.byte $ff,$20
	.word @ref19
	.byte $ff,$21
	.word @ref20
	.byte $ff,$1f
	.word @ref21
	.byte $ff,$1f
	.word @ref22
	.byte $ff,$1d
	.word @ref23
	.byte $ff,$20
	.word @ref19
	.byte $ff,$21
	.word @ref20
	.byte $ff,$1f
	.word @ref21
	.byte $ff,$1f
	.word @ref22
	.byte $ff,$1d
	.word @ref23
	.byte $ff,$20
	.word @ref19
	.byte $ff,$21
	.word @ref20
	.byte $ff,$1f
	.word @ref21
	.byte $ff,$1f
	.word @ref22
	.byte $fd
	.word @song0ch4loop


