FT_DPCM_PTR=$c000
	.export _menu_theme_music_data
;this file for FamiTone2 library generated by FamiStudio

_menu_theme_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument 00 (Duty 0)
	.word @env1, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 01 (Duty 2)
	.word @env1, @env0, @env0
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$08,$0f	;1 (Sample 1)
	.byte $02+.lobyte(FT_DPCM_PTR),$14,$0f	;2 (Sample 2)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;16 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;18 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;20 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;21 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;22 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;23 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;25 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;26 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;27 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;28 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;29 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;30 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;31 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;32 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;33 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;34 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;35 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;36 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;37 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62 
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63 

@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $cf,$7f,$00,$00

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
@ref0:
	.byte $82,$4c,$8d,$00,$9d,$5a,$8d,$00,$9d,$4e,$8d,$00,$8d
@ref1:
	.byte $8f,$5c,$8d,$00,$9d,$50,$8d,$00,$9d,$5e,$8d
@ref2:
	.byte $00,$9d,$52,$8d,$00,$9d,$60,$8d,$00,$9d
@ref3:
	.byte $52,$8d,$00,$b5,$5c,$8d,$00,$85,$52,$8d,$00,$8d
@ref4:
	.byte $a7,$52,$8d,$00,$85,$56,$8d,$00,$85,$52,$8d,$00,$85,$58,$8d
@ref5:
	.byte $00,$85,$52,$8d,$00,$85,$48,$8d,$00,$91,$50,$8d,$00,$91,$60,$8d,$00,$85
@ref6:
	.byte $58,$8d,$00,$b5,$58,$8d,$00,$85,$52,$8d,$00,$8d
@ref7:
	.byte $a7,$4e,$8d,$00,$85,$44,$8d,$00,$91,$44,$8d,$00,$89
@ref8:
	.byte $87,$44,$8d,$00,$85,$48,$8d,$00,$85,$48,$8d,$00,$85,$3e,$8d,$00,$9d
	.byte $ff,$0c
	.word @ref3
	.byte $ff,$0f
	.word @ref4
	.byte $ff,$12
	.word @ref5
	.byte $ff,$0c
	.word @ref6
	.byte $ff,$0d
	.word @ref7
	.byte $ff,$11
	.word @ref8
@ref9:
	.byte $3a,$8d,$00,$85,$40,$8d,$00,$85,$48,$8d,$00,$85,$44,$8d,$00,$85,$48,$8d,$00,$85,$56,$85
@ref10:
	.byte $87,$00,$85,$5c,$8d,$00,$85,$58,$8d,$00,$85,$52,$8d,$00,$85,$60,$8d,$00,$85,$52,$8d
@ref11:
	.byte $00,$85,$60,$8d,$00,$85,$52,$8d,$00,$b5,$48,$8d,$00,$85
	.byte $ff,$16
	.word @ref9
@ref12:
	.byte $87,$00,$85,$5c,$8d,$00,$85,$60,$8d,$00,$85,$6a,$8d,$00,$85,$5c,$8d,$00,$85,$52,$8d
@ref13:
	.byte $00,$85,$44,$8d,$00,$85,$3a,$8d,$00,$cd
	.byte $ff,$16
	.word @ref9
	.byte $ff,$15
	.word @ref10
	.byte $ff,$0e
	.word @ref11
	.byte $ff,$16
	.word @ref9
	.byte $ff,$15
	.word @ref12
	.byte $ff,$0a
	.word @ref13
@ref14:
	.byte $4c,$8d,$00,$b5,$56,$8d,$00,$85,$4c,$8d,$00,$8d
@ref15:
	.byte $a7,$4c,$8d,$00,$85,$50,$8d,$00,$85,$4c,$8d,$00,$85,$52,$8d
@ref16:
	.byte $00,$85,$4c,$8d,$00,$85,$42,$8d,$00,$91,$4a,$8d,$00,$91,$5a,$8d,$00,$85
@ref17:
	.byte $52,$8d,$00,$b5,$52,$8d,$00,$85,$4c,$8d,$00,$8d
@ref18:
	.byte $a7,$48,$8d,$00,$85,$3e,$8d,$00,$91,$3e,$8d,$00,$89
@ref19:
	.byte $87,$3e,$8d,$00,$85,$42,$8d,$00,$85,$42,$8d,$00,$85,$38,$8d,$00,$9d
	.byte $ff,$0c
	.word @ref14
	.byte $ff,$0f
	.word @ref15
	.byte $ff,$12
	.word @ref16
	.byte $ff,$0c
	.word @ref17
	.byte $ff,$0d
	.word @ref18
	.byte $ff,$11
	.word @ref19
@ref20:
	.byte $34,$8d,$00,$85,$3a,$8d,$00,$85,$42,$8d,$00,$85,$3e,$8d,$00,$85,$42,$8d,$00,$85,$50,$85
@ref21:
	.byte $87,$00,$85,$56,$8d,$00,$85,$52,$8d,$00,$85,$4c,$8d,$00,$85,$5a,$8d,$00,$85,$4c,$8d
@ref22:
	.byte $00,$85,$5a,$8d,$00,$85,$4c,$8d,$00,$b5,$42,$8d,$00,$85
	.byte $ff,$16
	.word @ref20
@ref23:
	.byte $87,$00,$85,$56,$8d,$00,$85,$5a,$8d,$00,$85,$64,$8d,$00,$85,$56,$8d,$00,$85,$4c,$8d
@ref24:
	.byte $00,$85,$3e,$8d,$00,$85,$34,$8d,$00,$cd
	.byte $ff,$16
	.word @ref20
	.byte $ff,$15
	.word @ref21
	.byte $ff,$0e
	.word @ref22
	.byte $ff,$16
	.word @ref20
	.byte $ff,$15
	.word @ref23
	.byte $ff,$0a
	.word @ref24
@ref25:
	.byte $4c,$8d,$00,$9d,$5a,$8d,$00,$9d,$4e,$8d,$00,$8d
	.byte $ff,$0b
	.word @ref1
	.byte $ff,$0a
	.word @ref2
	.byte $ff,$0c
	.word @ref3
	.byte $ff,$0f
	.word @ref4
	.byte $ff,$12
	.word @ref5
	.byte $ff,$0c
	.word @ref6
	.byte $ff,$0d
	.word @ref7
	.byte $ff,$11
	.word @ref8
	.byte $ff,$0c
	.word @ref3
	.byte $ff,$0f
	.word @ref4
	.byte $ff,$12
	.word @ref5
	.byte $ff,$0c
	.word @ref6
	.byte $ff,$0d
	.word @ref7
	.byte $ff,$11
	.word @ref8
	.byte $ff,$16
	.word @ref9
	.byte $ff,$15
	.word @ref10
	.byte $ff,$0e
	.word @ref11
	.byte $ff,$16
	.word @ref9
	.byte $ff,$15
	.word @ref12
	.byte $ff,$0a
	.word @ref13
	.byte $ff,$16
	.word @ref9
	.byte $ff,$15
	.word @ref10
	.byte $ff,$0e
	.word @ref11
	.byte $ff,$16
	.word @ref9
	.byte $ff,$15
	.word @ref12
	.byte $ff,$0a
	.word @ref13
	.byte $ff,$0c
	.word @ref14
	.byte $ff,$0f
	.word @ref15
	.byte $ff,$12
	.word @ref16
	.byte $ff,$0c
	.word @ref17
	.byte $ff,$0d
	.word @ref18
	.byte $ff,$11
	.word @ref19
	.byte $ff,$0c
	.word @ref14
	.byte $ff,$0f
	.word @ref15
	.byte $ff,$12
	.word @ref16
	.byte $ff,$0c
	.word @ref17
	.byte $ff,$0d
	.word @ref18
	.byte $ff,$11
	.word @ref19
	.byte $ff,$16
	.word @ref20
	.byte $ff,$15
	.word @ref21
	.byte $ff,$0e
	.word @ref22
	.byte $ff,$16
	.word @ref20
	.byte $ff,$15
	.word @ref23
	.byte $ff,$0a
	.word @ref24
	.byte $ff,$16
	.word @ref20
	.byte $ff,$15
	.word @ref21
	.byte $ff,$0e
	.word @ref22
	.byte $ff,$16
	.word @ref20
	.byte $ff,$15
	.word @ref23
	.byte $ff,$0a
	.word @ref24
	.byte $ff,$0c
	.word @ref25
	.byte $ff,$0b
	.word @ref1
	.byte $ff,$0a
	.word @ref2
	.byte $ff,$0c
	.word @ref3
	.byte $ff,$0f
	.word @ref4
	.byte $ff,$12
	.word @ref5
	.byte $ff,$0c
	.word @ref6
	.byte $ff,$0d
	.word @ref7
	.byte $ff,$11
	.word @ref8
	.byte $ff,$0c
	.word @ref3
@ref26:
	.byte $a7,$52,$8d,$00,$c5
@ref27:
	.byte $f9,$85
@ref28:
	.byte $f9,$85
@ref29:
	.byte $f9,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref30:
	.byte $82,$34,$8d,$00,$9d,$42,$8d,$00,$9d,$36,$8d,$00,$8d
@ref31:
	.byte $8f,$44,$8d,$00,$9d,$38,$8d,$00,$9d,$46,$8d
@ref32:
	.byte $00,$9d,$3a,$8d,$00,$9d,$48,$8d,$00,$9d
@ref33:
	.byte $40,$8d,$00,$cd,$4a,$8d,$00,$8d
@ref34:
	.byte $a7,$4a,$8d,$00,$85,$4e,$8d,$00,$9d,$4e,$8d
@ref35:
	.byte $00,$9d,$3e,$8d,$00,$91,$48,$8d,$00,$91,$50,$8d,$00,$85
@ref36:
	.byte $52,$8d,$00,$b5,$52,$8d,$00,$85,$4a,$8d,$00,$8d
@ref37:
	.byte $a7,$40,$8d,$00,$85,$3e,$8d,$00,$91,$3e,$8d,$00,$89
@ref38:
	.byte $87,$3e,$8d,$00,$e5
	.byte $ff,$08
	.word @ref33
	.byte $ff,$0b
	.word @ref34
	.byte $ff,$0e
	.word @ref35
	.byte $ff,$0c
	.word @ref36
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$05
	.word @ref38
@ref39:
	.byte $af,$40,$8d,$00,$b5,$4e,$85
@ref40:
	.byte $87,$00,$85,$56,$8d,$00,$85,$52,$8d,$00,$85,$48,$8d,$00,$85,$58,$8d,$00,$85,$48,$8d
@ref41:
	.byte $00,$85,$58,$8d,$00,$85,$48,$8d,$00,$cd
	.byte $ff,$07
	.word @ref39
@ref42:
	.byte $87,$00,$85,$56,$8d,$00,$85,$56,$8d,$00,$85,$58,$8d,$00,$85,$48,$8d,$00,$85,$40,$8d
@ref43:
	.byte $00,$85,$30,$8d,$00,$85,$28,$8d,$00,$cd
	.byte $ff,$07
	.word @ref39
	.byte $ff,$15
	.word @ref40
	.byte $ff,$0a
	.word @ref41
	.byte $ff,$07
	.word @ref39
	.byte $ff,$15
	.word @ref42
	.byte $ff,$0a
	.word @ref43
@ref44:
	.byte $3a,$8d,$00,$cd,$44,$8d,$00,$8d
@ref45:
	.byte $a7,$44,$8d,$00,$85,$48,$8d,$00,$9d,$48,$8d
@ref46:
	.byte $00,$9d,$38,$8d,$00,$91,$42,$8d,$00,$91,$4a,$8d,$00,$85
@ref47:
	.byte $4c,$8d,$00,$b5,$4c,$8d,$00,$85,$44,$8d,$00,$8d
@ref48:
	.byte $a7,$3a,$8d,$00,$85,$38,$8d,$00,$91,$38,$8d,$00,$89
@ref49:
	.byte $87,$38,$8d,$00,$e5
	.byte $ff,$08
	.word @ref44
	.byte $ff,$0b
	.word @ref45
	.byte $ff,$0e
	.word @ref46
	.byte $ff,$0c
	.word @ref47
	.byte $ff,$0d
	.word @ref48
	.byte $ff,$05
	.word @ref49
@ref50:
	.byte $af,$3a,$8d,$00,$b5,$48,$85
@ref51:
	.byte $87,$00,$85,$50,$8d,$00,$85,$4c,$8d,$00,$85,$42,$8d,$00,$85,$52,$8d,$00,$85,$42,$8d
@ref52:
	.byte $00,$85,$52,$8d,$00,$85,$42,$8d,$00,$cd
	.byte $ff,$07
	.word @ref50
@ref53:
	.byte $87,$00,$85,$50,$8d,$00,$85,$50,$8d,$00,$85,$52,$8d,$00,$85,$42,$8d,$00,$85,$3a,$8d
@ref54:
	.byte $00,$85,$2a,$8d,$00,$85,$22,$8d,$00,$cd
	.byte $ff,$07
	.word @ref50
	.byte $ff,$15
	.word @ref51
	.byte $ff,$0a
	.word @ref52
	.byte $ff,$07
	.word @ref50
	.byte $ff,$15
	.word @ref53
	.byte $ff,$0a
	.word @ref54
@ref55:
	.byte $34,$8d,$00,$9d,$42,$8d,$00,$9d,$36,$8d,$00,$8d
	.byte $ff,$0b
	.word @ref31
	.byte $ff,$0a
	.word @ref32
	.byte $ff,$08
	.word @ref33
	.byte $ff,$0b
	.word @ref34
	.byte $ff,$0e
	.word @ref35
	.byte $ff,$0c
	.word @ref36
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$05
	.word @ref38
	.byte $ff,$08
	.word @ref33
	.byte $ff,$0b
	.word @ref34
	.byte $ff,$0e
	.word @ref35
	.byte $ff,$0c
	.word @ref36
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$05
	.word @ref38
	.byte $ff,$07
	.word @ref39
	.byte $ff,$15
	.word @ref40
	.byte $ff,$0a
	.word @ref41
	.byte $ff,$07
	.word @ref39
	.byte $ff,$15
	.word @ref42
	.byte $ff,$0a
	.word @ref43
	.byte $ff,$07
	.word @ref39
	.byte $ff,$15
	.word @ref40
	.byte $ff,$0a
	.word @ref41
	.byte $ff,$07
	.word @ref39
	.byte $ff,$15
	.word @ref42
	.byte $ff,$0a
	.word @ref43
	.byte $ff,$08
	.word @ref44
	.byte $ff,$0b
	.word @ref45
	.byte $ff,$0e
	.word @ref46
	.byte $ff,$0c
	.word @ref47
	.byte $ff,$0d
	.word @ref48
	.byte $ff,$05
	.word @ref49
	.byte $ff,$08
	.word @ref44
	.byte $ff,$0b
	.word @ref45
	.byte $ff,$0e
	.word @ref46
	.byte $ff,$0c
	.word @ref47
	.byte $ff,$0d
	.word @ref48
	.byte $ff,$05
	.word @ref49
	.byte $ff,$07
	.word @ref50
	.byte $ff,$15
	.word @ref51
	.byte $ff,$0a
	.word @ref52
	.byte $ff,$07
	.word @ref50
	.byte $ff,$15
	.word @ref53
	.byte $ff,$0a
	.word @ref54
	.byte $ff,$07
	.word @ref50
	.byte $ff,$15
	.word @ref51
	.byte $ff,$0a
	.word @ref52
	.byte $ff,$07
	.word @ref50
	.byte $ff,$15
	.word @ref53
	.byte $ff,$0a
	.word @ref54
	.byte $ff,$0c
	.word @ref55
	.byte $ff,$0b
	.word @ref31
	.byte $ff,$0a
	.word @ref32
	.byte $ff,$08
	.word @ref33
	.byte $ff,$0b
	.word @ref34
	.byte $ff,$0e
	.word @ref35
	.byte $ff,$0c
	.word @ref36
	.byte $ff,$0d
	.word @ref37
	.byte $ff,$05
	.word @ref38
	.byte $ff,$08
	.word @ref33
@ref56:
	.byte $a7,$4a,$8d,$00,$c5
@ref57:
	.byte $f9,$85
@ref58:
	.byte $f9,$85
@ref59:
	.byte $f9,$85
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref60:
	.byte $80,$42,$dd,$44,$9d
@ref61:
	.byte $bf,$46,$bd
@ref62:
	.byte $9f,$48,$dd
@ref63:
	.byte $ab,$01,$52,$a9,$01,$40,$9d
@ref64:
	.byte $8b,$01,$4a,$a9,$01,$44,$a9,$01,$4e,$8d
@ref65:
	.byte $9b,$01,$3e,$a9,$01,$48,$a9,$00,$81
@ref66:
	.byte $48,$a9,$01,$52,$a9,$01,$40,$9d
	.byte $ff,$0a
	.word @ref64
	.byte $ff,$09
	.word @ref65
	.byte $ff,$08
	.word @ref66
	.byte $ff,$0a
	.word @ref64
	.byte $ff,$09
	.word @ref65
	.byte $ff,$08
	.word @ref66
	.byte $ff,$0a
	.word @ref64
	.byte $ff,$09
	.word @ref65
@ref67:
	.byte $40,$a9,$01,$4a,$a9,$01,$44,$9d
@ref68:
	.byte $8b,$01,$4e,$a9,$01,$48,$a9,$01,$52,$8d
@ref69:
	.byte $9b,$01,$48,$a9,$01,$52,$a9,$00,$81
	.byte $ff,$08
	.word @ref67
	.byte $ff,$0a
	.word @ref68
	.byte $ff,$09
	.word @ref69
	.byte $ff,$08
	.word @ref67
	.byte $ff,$0a
	.word @ref68
	.byte $ff,$09
	.word @ref69
	.byte $ff,$08
	.word @ref67
	.byte $ff,$0a
	.word @ref68
	.byte $ff,$09
	.word @ref69
@ref70:
	.byte $42,$a9,$01,$4c,$a9,$01,$3a,$9d
@ref71:
	.byte $8b,$01,$44,$a9,$01,$3e,$a9,$01,$48,$8d
@ref72:
	.byte $9b,$01,$38,$a9,$01,$42,$a9,$00,$81
	.byte $ff,$08
	.word @ref70
	.byte $ff,$0a
	.word @ref71
	.byte $ff,$09
	.word @ref72
	.byte $ff,$08
	.word @ref70
	.byte $ff,$0a
	.word @ref71
	.byte $ff,$09
	.word @ref72
	.byte $ff,$08
	.word @ref70
	.byte $ff,$0a
	.word @ref71
	.byte $ff,$09
	.word @ref72
@ref73:
	.byte $3a,$a9,$01,$44,$a9,$01,$3e,$9d
@ref74:
	.byte $8b,$01,$48,$a9,$01,$42,$a9,$01,$4c,$8d
@ref75:
	.byte $9b,$01,$42,$a9,$01,$4c,$a9,$00,$81
	.byte $ff,$08
	.word @ref73
	.byte $ff,$0a
	.word @ref74
	.byte $ff,$09
	.word @ref75
	.byte $ff,$08
	.word @ref73
	.byte $ff,$0a
	.word @ref74
	.byte $ff,$09
	.word @ref75
	.byte $ff,$08
	.word @ref73
	.byte $ff,$0a
	.word @ref74
	.byte $ff,$09
	.word @ref75
@ref76:
	.byte $42,$dd,$44,$9d
@ref77:
	.byte $bf,$46,$bd
@ref78:
	.byte $9f,$48,$dd
	.byte $ff,$07
	.word @ref63
	.byte $ff,$0a
	.word @ref64
	.byte $ff,$09
	.word @ref65
	.byte $ff,$08
	.word @ref66
	.byte $ff,$0a
	.word @ref64
	.byte $ff,$09
	.word @ref65
	.byte $ff,$08
	.word @ref66
	.byte $ff,$0a
	.word @ref64
	.byte $ff,$09
	.word @ref65
	.byte $ff,$08
	.word @ref66
	.byte $ff,$0a
	.word @ref64
	.byte $ff,$09
	.word @ref65
	.byte $ff,$08
	.word @ref67
	.byte $ff,$0a
	.word @ref68
	.byte $ff,$09
	.word @ref69
	.byte $ff,$08
	.word @ref67
	.byte $ff,$0a
	.word @ref68
	.byte $ff,$09
	.word @ref69
	.byte $ff,$08
	.word @ref67
	.byte $ff,$0a
	.word @ref68
	.byte $ff,$09
	.word @ref69
	.byte $ff,$08
	.word @ref67
	.byte $ff,$0a
	.word @ref68
	.byte $ff,$09
	.word @ref69
	.byte $ff,$08
	.word @ref70
	.byte $ff,$0a
	.word @ref71
	.byte $ff,$09
	.word @ref72
	.byte $ff,$08
	.word @ref70
	.byte $ff,$0a
	.word @ref71
	.byte $ff,$09
	.word @ref72
	.byte $ff,$08
	.word @ref70
	.byte $ff,$0a
	.word @ref71
	.byte $ff,$09
	.word @ref72
	.byte $ff,$08
	.word @ref70
	.byte $ff,$0a
	.word @ref71
	.byte $ff,$09
	.word @ref72
	.byte $ff,$08
	.word @ref73
	.byte $ff,$0a
	.word @ref74
	.byte $ff,$09
	.word @ref75
	.byte $ff,$08
	.word @ref73
	.byte $ff,$0a
	.word @ref74
	.byte $ff,$09
	.word @ref75
	.byte $ff,$08
	.word @ref73
	.byte $ff,$0a
	.word @ref74
	.byte $ff,$09
	.word @ref75
	.byte $ff,$08
	.word @ref73
	.byte $ff,$0a
	.word @ref74
	.byte $ff,$09
	.word @ref75
@ref79:
	.byte $42,$dd,$44,$9d
@ref80:
	.byte $bf,$46,$bd
@ref81:
	.byte $9f,$48,$dd
	.byte $ff,$07
	.word @ref63
	.byte $ff,$0a
	.word @ref64
	.byte $ff,$09
	.word @ref65
	.byte $ff,$08
	.word @ref66
	.byte $ff,$0a
	.word @ref64
	.byte $ff,$09
	.word @ref65
	.byte $ff,$08
	.word @ref66
@ref82:
	.byte $8b,$01,$4a,$a9,$00,$c1
@ref83:
	.byte $f9,$85
@ref84:
	.byte $f9,$85
@ref85:
	.byte $f9,$85
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref86:
	.byte $97,$80,$58,$83,$00,$a7,$58,$83,$00,$a7,$58,$83,$00
@ref87:
	.byte $a7,$58,$83,$00,$a7,$58,$83,$00,$9f
@ref88:
	.byte $87,$58,$83,$00,$a7,$58,$83,$00,$a7,$58,$83,$00,$8f
@ref89:
	.byte $58,$83,$00,$8f,$58,$8d,$00,$b5,$58,$83,$00,$8f,$58,$85
@ref90:
	.byte $87,$00,$b5,$58,$83,$00,$8f,$58,$8d,$00,$95
@ref91:
	.byte $9f,$58,$83,$00,$8f,$58,$8d,$00,$b5
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
@ref92:
	.byte $97,$58,$83,$00,$a7,$58,$83,$00,$a7,$58,$83,$00
	.byte $ff,$09
	.word @ref87
	.byte $ff,$0d
	.word @ref88
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0c
	.word @ref92
	.byte $ff,$09
	.word @ref87
	.byte $ff,$0d
	.word @ref88
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
	.byte $ff,$0b
	.word @ref90
	.byte $ff,$09
	.word @ref91
	.byte $ff,$0e
	.word @ref89
@ref93:
	.byte $87,$00,$f5
@ref94:
	.byte $f9,$85
@ref95:
	.byte $f9,$85
@ref96:
	.byte $f9,$85
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref97:
	.byte $02,$dd,$02,$9d
@ref98:
	.byte $bf,$02,$bd
@ref99:
	.byte $9f,$02,$dd
@ref100:
	.byte $02,$ad,$02,$95,$04,$95,$02,$9d
@ref101:
	.byte $8f,$02,$95,$04,$95,$02,$ad,$02,$8d
@ref102:
	.byte $87,$04,$95,$02,$ad,$02,$95,$04,$95
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
@ref103:
	.byte $87,$04,$95,$02,$ad,$04,$95,$04,$95
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
@ref104:
	.byte $8f,$04,$95,$04,$95,$02,$ad,$02,$8d
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref103
@ref105:
	.byte $02,$dd,$02,$9d
@ref106:
	.byte $bf,$02,$bd
@ref107:
	.byte $9f,$02,$dd
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref104
	.byte $ff,$09
	.word @ref103
@ref108:
	.byte $02,$dd,$02,$9d
@ref109:
	.byte $bf,$02,$bd
@ref110:
	.byte $9f,$02,$dd
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref102
	.byte $ff,$08
	.word @ref100
	.byte $ff,$09
	.word @ref101
	.byte $ff,$09
	.word @ref103
	.byte $ff,$08
	.word @ref100
@ref111:
	.byte $8f,$02,$95,$04,$d5
@ref112:
	.byte $f9,$85
@ref113:
	.byte $f9,$85
@ref114:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
