
;this file for FamiTone2 libary generated by FamiStudio

_sfx_sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_song_1
        .word @sfx_ntsc_song_2

@sfx_ntsc_song_1:
	.byte $82,$01,$81,$ab,$80,$39,$89,$f0,$04,$81,$3f,$80,$36,$01,$81,$1c
	.byte $01,$80,$35,$02,$80,$34,$02,$80,$33,$02,$80,$32,$02,$80,$31,$02
	.byte $00
        
@sfx_ntsc_song_2:
	.byte $85,$00,$84,$70,$83,$be,$89,$f0,$02,$83,$bd,$01,$84,$53,$83,$be
	.byte $02,$83,$bd,$01,$84,$38,$01,$83,$bc,$02,$84,$29,$83,$bb,$01,$83
	.byte $ba,$02,$83,$b9,$02,$83,$b8,$02,$83,$b7,$01,$83,$b6,$02,$83,$b5
	.byte $02,$83,$b4,$02,$83,$b3,$01,$83,$b2,$02,$83,$b1,$02,$00

.export _sfx_sounds